/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace account {
    // Declare a service for each controller you have
    export interface AccountService {
        // Declare an rpc for each method that is called via gRPC
        findOne(data: AccountId, metadata?: Metadata): Observable<Account>;
        findMany(data: AccountId, metadata?: Metadata): Observable<AccountResult>;
        create(data: Account, metadata?: Metadata): Observable<Account>;
        update(data: Account, metadata?: Metadata): Observable<AccountArray>;
    }
    // Declare the types used above
    export interface Account {
        id?: number;
        accountCode?: string;
        title?: string;
        parentCode?: string;
        isActive?: boolean;
    }
    export interface AccountArray {
        data?: account.Account[];
    }
    export interface AccountResult {
        rows?: account.Account[];
        count?: number;
    }
    export interface AccountId {
        id?: number;
    }
}

